version: '3.8'
services:
  app.gateway:
    build:
      context: .
      dockerfile: ./src/gateway/Dockerfile
    image: appgameway
    ports:
      - '80:80' # Connect localhost 80 port to container 80 port
    environment: 
      - WEB_APP_PORT=80
    depends_on: 
      - app.api
      - app.ui
  app.api:
    build:
      context: .
      dockerfile: ./src/App.API/API/Dockerfile
      target: final
    image: 'appapi'
    ports:
      - '8080:80'
      - '8081:443'
    restart: unless-stopped
    environment:       
      - OPCUA_MODE=0 # When OPC-UA Client connected should be =1
      # - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - db-data:/var/lib/sqlite/data
  app.ui:
    build:
      context: .
      dockerfile: ./src/App.UI/Dockerfile
    image: 'appui'
    ports:
      - '8090:80'
      - '8091:443'
    restart: unless-stopped
    environment: 
      - API_URL=/api

volumes:
  db-data: